simbot:
  # 是否在bot注册完成后自动启动他们。
  # 默认为 true
  auto-start-bots: true

  # 自定义配置bot资源文件的扫描路径。
  # 默认为 'classpath:simbot-bots/*.bot*'
  bot-configuration-resources:
    - 'classpath:simbot-bots/*.bot*'

  # 如果需要，此处配置扫描顶层函数形式的 Binder Factory。
  # 默认不扫描
  # top-level-binder-scan-package:
  #   - 'example.binder.foo'
  #   - 'example.binder.bar'

  # 如果需要，此处配置扫描顶层函数形式的监听函数。
  # 默认不扫描
  # top-level-listener-scan-package:
  #   - 'example.listener.foo'
  #   - 'example.listener.bar'
#  default-master-qq: 主人号码
#  default-notice-groups: bot生效群组
#  default-login-msg: bot上线消息内容
  default-master-qq: 67252271
  default-notice-groups: 710117186
  default-login-msg: '您的小可爱已上线~'
